name: Create and publish a Docker image

permissions:
  contents: read

on:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: metalock
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/crf-paris15/twilio-matrix-bridge

      - name: Build and push Docker image for twilio-matrix-bridge
        id: pushtwilio
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.metalock.outputs.tags }}
          labels: ${{ steps.metalock.outputs.labels }}
          build-args: |
            GIT_TAG=${{ github.ref_name }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v4
        with:
          subject-name: ${{ env.REGISTRY }}/crf-paris15/twilio-matrix-bridge
          subject-digest: ${{ steps.pushtwilio.outputs.digest }}
          push-to-registry: true
